<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CavemanTcp" Version="2.0.9" />
    <PackageReference Include="IpMatcher" Version="1.0.5" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="RegexMatcher" Version="1.0.9" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    <PackageReference Include="Timestamps" Version="1.0.11" />
    <PackageReference Include="UrlMatcher" Version="3.0.1" />
    <PackageReference Include="Watson" Version="6.3.9" />
    <PackageReference Include="Watson.Core" Version="6.3.9" />
    <PackageReference Include="Watson.Lite" Version="6.3.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Com\ApplicationActivationManager.cs" />
    <Compile Include="Com\IApplicationActivationManager.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\icon.ico" />
    <Content Include="Assets\logo.ico" />
    <Content Include="Assets\watson.ico" />
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
    <None Include="LICENSE.md" />
  </ItemGroup>

</Project>